version: "3"

services:
  app:
    image: jekyll/jekyll:latest
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - "./app:/srv/jekyll"
    tty: true
    # entrypoint: ["bash", "/srv/jekyll/init.sh"]
    entrypoint: ["jekyll", "serve"]
